import {
  Home,
  LayoutDashboard,
  Trophy,
  Bug,
  Sparkles,
  Hash,
  Percent,
  Table2,
  Share2,
  GitBranch,
  Layers,
  Coins,
  Triangle,
  BookOpen,
  Star,
  Clock,
  Settings,
  Info,
  Search,
  Calculator,
  RefreshCw,
  Binary,
  FileCode2,
  Cpu,
  ArrowLeftRight,
  Rows,
  BarChart2,
  SortAsc,
  Copy,
  Shuffle,
  AlignLeft,
  FileCheck,
  Play,
  ListCollapse,
  Type,
  Grid3X3,
  Network,
  HelpCircle,
  TrendingUp,
  Compass,
  Zap,
  Sliders,
  FolderSync,
  ShieldCheck,
  Divide,
  GitCommit,
  RotateCcw,
  Columns,
  X,
  RotateCw,
  Droplet,
  Navigation,
  Activity,
  Bookmark,
  Scissors,
  FolderOpen,
  ShoppingBag,
  FileText,
  Grid
} from "lucide-react";

export interface NavItem {
  title: string;
  href: string;
  icon: any;
  children?: NavItem[];
}

export const sidebarItems: NavItem[] = [
  { title: "Home", href: "/", icon: Home },
  { title: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  {
    title: "Contest Utilities",
    href: "/contest-utilities",
    icon: Trophy,
    children: [
      { title: "Calculator", href: "/contest-utilities/calculator", icon: Calculator },
      { title: "Base Converter", href: "/contest-utilities/base-converter", icon: RefreshCw },
      { title: "Binary Calculator", href: "/contest-utilities/binary-calculator", icon: Binary },
      { title: "ASCII Table", href: "/contest-utilities/ascii-table", icon: Hash },
      { title: "Roman Converter", href: "/contest-utilities/roman-converter", icon: BookOpen },
      { title: "Expression Evaluator", href: "/contest-utilities/expression-evaluator", icon: FileCode2 },
      { title: "BigInt Calculator", href: "/contest-utilities/bigint-calculator", icon: Layers },
      { title: "Overflow Checker", href: "/contest-utilities/overflow-checker", icon: Cpu },
    ],
  },
  {
    title: "Debug Tools",
    href: "/debug-tools",
    icon: Bug,
    children: [
      { title: "Output Comparer", href: "/debug-tools/output-comparer", icon: ArrowLeftRight },
      { title: "Line Difference", href: "/debug-tools/line-diff", icon: Rows },
      { title: "Character Difference", href: "/debug-tools/character-diff", icon: Binary },
      { title: "Frequency Comparator", href: "/debug-tools/frequency-compare", icon: BarChart2 },
      { title: "Sort Checker", href: "/debug-tools/sort-checker", icon: SortAsc },
      { title: "Duplicate Finder", href: "/debug-tools/duplicate-finder", icon: Copy },
      { title: "Array Shuffler", href: "/debug-tools/shuffle-array", icon: Shuffle },
      { title: "Whitespace Checker", href: "/debug-tools/whitespace-checker", icon: AlignLeft },
      { title: "Input Validator", href: "/debug-tools/input-validator", icon: FileCheck },
      { title: "Stress Test (MVP)", href: "/debug-tools/stress-test", icon: Play },
      { title: "Memory Estimator", href: "/debug-tools/memory-estimator", icon: Cpu },
    ],
  },
  {
    title: "Test Generator",
    href: "/test-generator",
    icon: Sparkles,
    children: [
      { title: "Random Integer", href: "/test-generator/random-integer", icon: Hash },
      { title: "Random Array", href: "/test-generator/random-array", icon: ListCollapse },
      { title: "Random String", href: "/test-generator/random-string", icon: Type },
      { title: "Random Matrix", href: "/test-generator/random-matrix", icon: Grid3X3 },
      { title: "Random Permutation", href: "/test-generator/random-permutation", icon: Shuffle },
      { title: "Random Graph", href: "/test-generator/random-graph", icon: Network },
      { title: "Random Tree", href: "/test-generator/random-tree", icon: GitBranch },
      { title: "Random Queries", href: "/test-generator/random-query", icon: HelpCircle },
      { title: "Random Interval", href: "/test-generator/random-interval", icon: TrendingUp },
      { title: "Coordinate Generator", href: "/test-generator/coordinate-generator", icon: Compass },
      { title: "Edge Case Generator", href: "/test-generator/edge-case-generator", icon: Zap },
      { title: "Constraint Builder", href: "/test-generator/constraint-builder", icon: Sliders },
      { title: "Batch Generator", href: "/test-generator/batch-generator", icon: FolderSync },
    ],
  },
  {
    title: "Number Theory",
    href: "/number-theory",
    icon: Percent,
    children: [
      { title: "Prime Checker", href: "/number-theory/prime-checker", icon: ShieldCheck },
      { title: "Sieve of Eratosthenes", href: "/number-theory/sieve", icon: Layers },
      { title: "Segmented Sieve", href: "/number-theory/segmented-sieve", icon: ListCollapse },
      { title: "Prime Factorization", href: "/number-theory/factorization", icon: Binary },
      { title: "Divisors Calculator", href: "/number-theory/divisors", icon: Divide },
      { title: "GCD & LCM Calculator", href: "/number-theory/gcd-lcm", icon: GitCommit },
      { title: "Extended Euclidean Solver", href: "/number-theory/extended-euclid", icon: Calculator },
      { title: "Modular Exponentiation", href: "/number-theory/modular-exponentiation", icon: TrendingUp },
      { title: "Modular Inverse Solver", href: "/number-theory/modular-inverse", icon: RotateCcw },
      { title: "Euler Totient Solver", href: "/number-theory/euler-phi", icon: HelpCircle },
      { title: "Möbius Function Solver", href: "/number-theory/mobius", icon: Sliders },
      { title: "Chinese Remainder Theorem", href: "/number-theory/crt", icon: Columns },
      { title: "Bitwise Playground", href: "/number-theory/bitwise-playground", icon: Cpu },
      { title: "Gray Code Generator", href: "/number-theory/gray-code", icon: Shuffle },
      { title: "XOR Playground", href: "/number-theory/xor-playground", icon: Zap },
    ],
  },
  {
    title: "Strings",
    href: "/string-laboratory",
    icon: Hash,
    children: [
      { title: "Character Frequency", href: "/string-laboratory/frequency-counter", icon: BarChart2 },
      { title: "Palindrome Checker", href: "/string-laboratory/palindrome", icon: ShieldCheck },
      { title: "Reverse String", href: "/string-laboratory/reverse", icon: Shuffle },
      { title: "String Rotation", href: "/string-laboratory/rotation", icon: RefreshCw },
      { title: "Anagram Checker", href: "/string-laboratory/anagram", icon: GitCommit },
      { title: "Substring Search", href: "/string-laboratory/substring-search", icon: Search },
      { title: "Prefix Function (KMP)", href: "/string-laboratory/prefix-function", icon: Binary },
      { title: "Z Function", href: "/string-laboratory/z-function", icon: Cpu },
      { title: "Rolling Hash", href: "/string-laboratory/rolling-hash", icon: Layers },
      { title: "Edit Distance (Levenshtein)", href: "/string-laboratory/edit-distance", icon: Grid3X3 },
      { title: "Longest Common Prefix", href: "/string-laboratory/longest-common-prefix", icon: Sliders },
      { title: "Longest Common Subsequence", href: "/string-laboratory/longest-common-subsequence", icon: Columns },
      { title: "Longest Palindromic Substring", href: "/string-laboratory/longest-palindrome", icon: TrendingUp },
      { title: "Suffix Array", href: "/string-laboratory/suffix-array", icon: ListCollapse },
      { title: "Aho-Corasick Trie", href: "/string-laboratory/aho-corasick", icon: Network },
    ],
  },
  {
    title: "Matrix",
    href: "/matrix",
    icon: Table2,
    children: [
      { title: "Matrix Generator", href: "/matrix/matrix-generator", icon: Sliders },
      { title: "Matrix Transpose", href: "/matrix/transpose", icon: RefreshCw },
      { title: "Matrix Rotation", href: "/matrix/rotation", icon: RotateCw },
      { title: "Matrix Multiplication", href: "/matrix/multiplication", icon: X },
      { title: "Identity Matrix", href: "/matrix/identity", icon: Grid3X3 },
      { title: "Prefix Sum Matrix", href: "/matrix/prefix-sum", icon: Layers },
      { title: "Matrix Exponentiation", href: "/matrix/matrix-power", icon: TrendingUp },
      { title: "Matrix Determinant", href: "/matrix/determinant", icon: Calculator },
      { title: "Matrix Rank", href: "/matrix/rank", icon: BarChart2 },
      { title: "Spiral Traversal", href: "/matrix/spiral", icon: RotateCcw },
      { title: "Diagonal Traversal", href: "/matrix/diagonal", icon: Shuffle },
      { title: "Grid BFS", href: "/matrix/grid-bfs", icon: Network },
      { title: "Grid DFS", href: "/matrix/grid-dfs", icon: GitBranch },
      { title: "Flood Fill", href: "/matrix/flood-fill", icon: Droplet },
      { title: "Pathfinding Grid", href: "/matrix/pathfinding", icon: Navigation },
    ],
  },
  {
    title: "Graph",
    href: "/graph",
    icon: Share2,
    children: [
      { title: "BFS Traversal", href: "/graph/bfs", icon: Network },
      { title: "DFS Traversal", href: "/graph/dfs", icon: GitBranch },
      { title: "Dijkstra Solver", href: "/graph/dijkstra", icon: Navigation },
      { title: "Bellman-Ford Solver", href: "/graph/bellman-ford", icon: Activity },
      { title: "Floyd-Warshall Matrix", href: "/graph/floyd-warshall", icon: Calculator },
      { title: "Topological Sort", href: "/graph/topological-sort", icon: Layers },
      { title: "Prim's MST", href: "/graph/prim", icon: TrendingUp },
      { title: "Kruskal's MST", href: "/graph/kruskal", icon: Sliders },
      { title: "DSU / Union-Find", href: "/graph/union-find", icon: Settings },
      { title: "Bipartite Checker", href: "/graph/bipartite", icon: Bookmark },
      { title: "Critical Bridges", href: "/graph/bridges", icon: Scissors },
      { title: "Articulation Points", href: "/graph/articulation", icon: Share2 },
      { title: "Kosaraju SCC", href: "/graph/scc", icon: FolderOpen },
      { title: "Graph Properties", href: "/graph/graph-properties", icon: Calculator },
    ],
  },
  {
    title: "Trees",
    href: "/tree",
    icon: GitBranch,
    children: [
      { title: "Tree Traversals", href: "/tree/binary-tree", icon: GitBranch },
      { title: "Binary Search Tree", href: "/tree/bst", icon: Settings },
      { title: "AVL Tree", href: "/tree/avl", icon: ShieldCheck },
      { title: "Binary Heap", href: "/tree/heap", icon: TrendingUp },
      { title: "Segment Tree", href: "/tree/segment-tree", icon: Activity },
      { title: "Lazy Segment Tree", href: "/tree/lazy-segment-tree", icon: Sliders },
      { title: "Fenwick Tree", href: "/tree/fenwick", icon: Calculator },
      { title: "Trie (Prefix Tree)", href: "/tree/trie", icon: FolderOpen },
      { title: "Lowest Common Ancestor", href: "/tree/lca", icon: Layers },
      { title: "Euler Tour DFS", href: "/tree/euler-tour", icon: Info },
      { title: "Tree Diameter", href: "/tree/diameter", icon: TrendingUp },
      { title: "Centroid Decomposition", href: "/tree/centroid", icon: Layers },
    ],
  },
  {
    title: "Dynamic Programming",
    href: "/dynamic-programming",
    icon: Layers,
    children: [
      { title: "0/1 Knapsack", href: "/dynamic-programming/knapsack", icon: ShoppingBag },
      { title: "Coin Change", href: "/dynamic-programming/coin-change", icon: Coins },
      { title: "LCS Subsequence", href: "/dynamic-programming/lcs", icon: FileText },
      { title: "LIS Sequence", href: "/dynamic-programming/lis", icon: TrendingUp },
      { title: "Edit Distance", href: "/dynamic-programming/edit-distance", icon: Scissors },
      { title: "Matrix Chain", href: "/dynamic-programming/matrix-chain", icon: Calculator },
      { title: "Subset Sum", href: "/dynamic-programming/subset-sum", icon: Grid },
      { title: "Rod Cutting", href: "/dynamic-programming/rod-cutting", icon: Scissors },
      { title: "Partition Problem", href: "/dynamic-programming/partition", icon: Grid },
      { title: "Memoization", href: "/dynamic-programming/memoization", icon: Info },
      { title: "Tabulation", href: "/dynamic-programming/tabulation", icon: Sliders },
      { title: "Space Optimization", href: "/dynamic-programming/space-optimization", icon: Layers },
      { title: "Digit DP", href: "/dynamic-programming/digit-dp", icon: Calculator },
      { title: "Tree DP", href: "/dynamic-programming/tree-dp", icon: GitBranch },
      { title: "Bitmask DP", href: "/dynamic-programming/bitmask-dp", icon: Layers },
      { title: "Travelling Salesman", href: "/dynamic-programming/tsp", icon: Sliders },
    ],
  },
  { title: "Greedy", href: "/greedy", icon: Coins },
  { title: "Geometry", href: "/geometry", icon: Triangle },
  { title: "Search", href: "/search", icon: Search },
  { title: "Quick Reference", href: "/quick-reference", icon: BookOpen },
  { title: "Favorites", href: "/favorites", icon: Star },
  { title: "Recent", href: "/recent", icon: Clock },
  { title: "Settings", href: "/settings", icon: Settings },
  { title: "About", href: "/about", icon: Info },
];
