import {
  Home,
  LayoutDashboard,
  Trophy,
  Bug,
  Sparkles,
  Hash,
  Percent,
  Table2,
  Share2,
  GitBranch,
  Layers,
  Coins,
  Triangle,
  BookOpen,
  Star,
  Clock,
  Settings,
  Info,
  Search,
  Calculator,
  RefreshCw,
  Binary,
  FileCode2,
  Cpu,
  ArrowLeftRight,
  Rows,
  BarChart2,
  SortAsc,
  Copy,
  Shuffle,
  AlignLeft,
  FileCheck,
  Play
} from "lucide-react";

export interface NavItem {
  title: string;
  href: string;
  icon: any;
  children?: NavItem[];
}

export const sidebarItems: NavItem[] = [
  { title: "Home", href: "/", icon: Home },
  { title: "Dashboard", href: "/dashboard", icon: LayoutDashboard },
  {
    title: "Contest Utilities",
    href: "/contest-utilities",
    icon: Trophy,
    children: [
      { title: "Calculator", href: "/contest-utilities/calculator", icon: Calculator },
      { title: "Base Converter", href: "/contest-utilities/base-converter", icon: RefreshCw },
      { title: "Binary Calculator", href: "/contest-utilities/binary-calculator", icon: Binary },
      { title: "ASCII Table", href: "/contest-utilities/ascii-table", icon: Hash },
      { title: "Roman Converter", href: "/contest-utilities/roman-converter", icon: BookOpen },
      { title: "Expression Evaluator", href: "/contest-utilities/expression-evaluator", icon: FileCode2 },
      { title: "BigInt Calculator", href: "/contest-utilities/bigint-calculator", icon: Layers },
      { title: "Overflow Checker", href: "/contest-utilities/overflow-checker", icon: Cpu },
    ],
  },
  {
    title: "Debug Tools",
    href: "/debug-tools",
    icon: Bug,
    children: [
      { title: "Output Comparer", href: "/debug-tools/output-comparer", icon: ArrowLeftRight },
      { title: "Line Difference", href: "/debug-tools/line-diff", icon: Rows },
      { title: "Character Difference", href: "/debug-tools/character-diff", icon: Binary },
      { title: "Frequency Comparator", href: "/debug-tools/frequency-compare", icon: BarChart2 },
      { title: "Sort Checker", href: "/debug-tools/sort-checker", icon: SortAsc },
      { title: "Duplicate Finder", href: "/debug-tools/duplicate-finder", icon: Copy },
      { title: "Array Shuffler", href: "/debug-tools/shuffle-array", icon: Shuffle },
      { title: "Whitespace Checker", href: "/debug-tools/whitespace-checker", icon: AlignLeft },
      { title: "Input Validator", href: "/debug-tools/input-validator", icon: FileCheck },
      { title: "Stress Test (MVP)", href: "/debug-tools/stress-test", icon: Play },
      { title: "Memory Estimator", href: "/debug-tools/memory-estimator", icon: Cpu },
    ],
  },
  { title: "Test Generator", href: "/generator", icon: Sparkles },
  { title: "Strings", href: "/strings", icon: Hash },
  { title: "Number Theory", href: "/number-theory", icon: Percent },
  { title: "Matrix", href: "/matrix", icon: Table2 },
  { title: "Graph", href: "/graph", icon: Share2 },
  { title: "Tree", href: "/tree", icon: GitBranch },
  { title: "Dynamic Programming", href: "/dp", icon: Layers },
  { title: "Greedy", href: "/greedy", icon: Coins },
  { title: "Geometry", href: "/geometry", icon: Triangle },
  { title: "Search", href: "/search", icon: Search },
  { title: "Quick Reference", href: "/quick-reference", icon: BookOpen },
  { title: "Favorites", href: "/favorites", icon: Star },
  { title: "Recent", href: "/recent", icon: Clock },
  { title: "Settings", href: "/settings", icon: Settings },
  { title: "About", href: "/about", icon: Info },
];
